backend/controllers/SiteController.php
<?php
namespace backend\controllers;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
//use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;
use backend\models\SignupForm;
use backend\models\ContactForm;
use common\components\Controller;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
       if (!\Yii::$app->user->isGuest) {
         if(1==1){
        return $this->render('index');
         }
         else{
          //enabled
            $this->layout="mainb";
          return $this->render('indexb');
         }
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
         public function actionDashboard()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('dashboard');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
      public function actionPeople()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('people');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
   public function actionChildren()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('children');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
   public function actionLookup()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('lookup');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
      public function actionAttendance()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('attendance');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
    public function actionOffering()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('offering');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
   public function actionGroup()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('group');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
 public function actionClientshome()
    {
        return $this->render('indexclients');
    }
    public function actionMghome()
    {
        return $this->render('indexmg');
    }
    public function actionPshome()
    {
        return $this->render('indexps');
    }
    public function actionChome()
    {
        return $this->render('indexc');
    }
     public function actionNhome($id)
    {
        return $this->render('indexnomotor',["clientId"=>$id]);
    }
    
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
          $this->layout="main_home";
        if (!Yii::$app->user->isGuest) {
              $this->layout="main_home";
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

     return $this->redirect(['login']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
  public function actionChurch()
    {
       if (!\Yii::$app->user->isGuest) {
        return $this->render('church');
         }  else {
     $this->layout="main_home";
      return $this->redirect(['login']);            
         }
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

class SiteController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        if (\Yii::$app->user->isGuest) {
            $this->layout = "main_public";
            return $this->redirect(['login']);
        } else {
            $this->layout = "main_private";
            return $this->render('index');
        }
    }

    public function actionLogin() {
        if (Yii::$app->user->isGuest) {
            $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->goBack();
            } else {
                $this->layout = "main_public";
                return $this->render('login', ['model' => $model]);
            }
        } else {
            //$this->layout = "main_private";
            return $this->goHome();
        }
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->redirect(['login']);
    }

    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            if (Yii::$app->user->isGuest) {
                $this->layout = "main_public";
            } else {
                $this->layout = "main_private";
            }
            return $this->render('contact', ['model' => $model,]);
        }
    }

    public function actionAbout() {
        if (Yii::$app->user->isGuest) {
            $this->layout = "main_public";
        } else {
            $this->layout = "main_private";
        }
        return $this->render('about');
    }

    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user == $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        $this->layout = "main_public";
        return $this->render('signup', ['model' => $model,]);
    }

    public function actionRequestPasswordReset() {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        $this->layout = "main_public";
        return $this->render('requestPasswordResetToken', ['model' => $model,]);
    }

    public function actionResetPassword($token) {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        $this->layout = "main_public";
        return $this->render('resetPassword', ['model' => $model,]);
    }

}

backend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

backend/views/site/attendance.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
//$this->title = 'ASSETS  MANAGEMENT SYSTEM';
$this->title = 'Attendance Home Page';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
.icon-btn {
    height: 70px;
    width: 50px;
    margin: 10px 0px 10px 0px;
    border: 1px solid #ddd;
    padding: 16px 0px 0px 0px;
    background-color: #fafafa !important;
    background-image: none !important;
    filter: none !important;
    -webkit-box-shadow: none !important;
    -moz-box-shadow: none !important;
    box-shadow: none !important;
    display: block !important;
    color: #646464 !important;
    text-shadow: none !important;
    text-align: center;
    cursor: pointer;
    position: relative;
    -webkit-transition: all 0.3s ease !important;
    -moz-transition: all 0.3s ease !important;
    -ms-transition: all 0.3s ease !important;
    -o-transition: all 0.3s ease !important;
    transition: all 0.3s ease !important;
}

</style>
 <div class="box box-info">
            <div class="box-header with-border">
               <h3 class="box-title">Attendance Home Page</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
             <div class="row-fluid">
                   <a href="<?= Yii::$app->urlManager->createUrl(['serviceattend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/Logbook.png') ?></i>
                                        <div>Service</div>

                                </a>
                       <a href="<?= Yii::$app->urlManager->createUrl(['zonepattend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/zone.png') ?></i>
                                        <div>Zone</div>

                                </a>
                  <a href="<?= Yii::$app->urlManager->createUrl(['deaconpattend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/role.png') ?></i>
                                        <div>Deacondry</div>

                                </a>
                            
                  </div>
               
                        <div class="row-fluid">
                                 <a href="<?= Yii::$app->urlManager->createUrl(['grouppattend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/group12.png') ?></i>
                                        <div>Group</div>

                                </a>
                    <a href="<?= Yii::$app->urlManager->createUrl(['ministrypattend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/TaskManage.png') ?></i>
                                        <div>Ministry</div>

                                </a>
                              
                      
                      
                              </div>
                             </div>
                   
                </div>     

backend/views/site/children.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
//$this->title = 'ASSETS  MANAGEMENT SYSTEM';
$this->title = 'Children Home Page';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
.icon-btn {
    height: 70px;
    width: 50px;
    margin: 10px 0px 10px 0px;
    border: 1px solid #ddd;
    padding: 16px 0px 0px 0px;
    background-color: #fafafa !important;
    background-image: none !important;
    filter: none !important;
    -webkit-box-shadow: none !important;
    -moz-box-shadow: none !important;
    box-shadow: none !important;
    display: block !important;
    color: #646464 !important;
    text-shadow: none !important;
    text-align: center;
    cursor: pointer;
    position: relative;
    -webkit-transition: all 0.3s ease !important;
    -moz-transition: all 0.3s ease !important;
    -ms-transition: all 0.3s ease !important;
    -o-transition: all 0.3s ease !important;
    transition: all 0.3s ease !important;
}

</style>
 <div class="box box-info">
            <div class="box-header with-border">
               <h3 class="box-title">Children Home Page</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
             <div class="row-fluid">
                   <a href="<?= Yii::$app->urlManager->createUrl(['children/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/Users.png') ?></i>
                                        <div>Children</div>

                                </a>
                       <a href="<?= Yii::$app->urlManager->createUrl(['childioffer/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/individualoffering.jpg') ?></i>
                                        <div>Indi Offering</div>

                                </a>
                  <a href="<?= Yii::$app->urlManager->createUrl(['childgoffer/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/generalofferinh.jpg') ?></i>
                                        <div>General Offering</div>

                                </a>
                                <a href="<?= Yii::$app->urlManager->createUrl(['childexpense/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/payment.png') ?></i>
                                        <div>Expense</div>

                                </a>
                  </div>
               
                        <div class="row-fluid">
                         
                    <a href="<?= Yii::$app->urlManager->createUrl(['childpattend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/jobcardassign.png') ?></i>
                                        <div>Attendance</div>

                                </a>
                               <a href="<?= Yii::$app->urlManager->createUrl(['childgttend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/jobcardassign.png') ?></i>
                                        <div>General Attendance</div>

                                </a>
                     <a href="<?= Yii::$app->urlManager->createUrl(['childgevent/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/Logbook.png') ?></i>
                                        <div>Events</div>

                                </a>        
                      
                      
                              </div>
                             </div>
                   
                </div>     

backend/views/site/church.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
//$this->title = 'ASSETS  MANAGEMENT SYSTEM';
$this->title = 'Church Home Page';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
.icon-btn {
    height: 70px;
    width: 50px;
    margin: 10px 0px 10px 0px;
    border: 1px solid #ddd;
    padding: 16px 0px 0px 0px;
    background-color: #fafafa !important;
    background-image: none !important;
    filter: none !important;
    -webkit-box-shadow: none !important;
    -moz-box-shadow: none !important;
    box-shadow: none !important;
    display: block !important;
    color: #646464 !important;
    text-shadow: none !important;
    text-align: center;
    cursor: pointer;
    position: relative;
    -webkit-transition: all 0.3s ease !important;
    -moz-transition: all 0.3s ease !important;
    -ms-transition: all 0.3s ease !important;
    -o-transition: all 0.3s ease !important;
    transition: all 0.3s ease !important;
}

</style>
 <div class="box box-info">
            <div class="box-header with-border">
               <h3 class="box-title">Church Home Page</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
             <div class="row-fluid">
            
                       <a href="<?= Yii::$app->urlManager->createUrl(['pastors/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/individualoffering.jpg') ?></i>
                                        <div>Pastor</div>

                                </a>
                   <a href="<?= Yii::$app->urlManager->createUrl(['elder/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/generalofferinh.jpg') ?></i>
                                        <div>Elder</div>

                                </a>
                       
          
                           
                     
                    <a href="<?= Yii::$app->urlManager->createUrl(['childpattend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/jobcardassign.png') ?></i>
                                        <div>Church Event</div>

                                </a>
                               <a href="<?= Yii::$app->urlManager->createUrl(['childgttend/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/jobcardassign.png') ?></i>
                                        <div>Church Plan</div>

                                </a>
                          </div>
                             </div>
                   
                </div>     

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
//$this->title = 'ASSETS  MANAGEMENT SYSTEM';
//$this->title = 'About';
//$this->params['breadcrumbs'][] = $this->title;
?>
<style>
.icon-btn {
    height: 70px;
    width: 50px;
    margin: 10px 0px 10px 0px;
    border: 1px solid #ddd;
    padding: 16px 0px 0px 0px;
    background-color: #fafafa !important;
    background-image: none !important;
    filter: none !important;
    -webkit-box-shadow: none !important;
    -moz-box-shadow: none !important;
    box-shadow: none !important;
    display: block !important;
    color: #646464 !important;
    text-shadow: none !important;
    text-align: center;
    cursor: pointer;
    position: relative;
    -webkit-transition: all 0.3s ease !important;
    -moz-transition: all 0.3s ease !important;
    -ms-transition: all 0.3s ease !important;
    -o-transition: all 0.3s ease !important;
    transition: all 0.3s ease !important;
}

</style>
 <div class="box box-info">
            <div class="box-header with-border">
               <h3 class="box-title">Home Page</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
             <div class="row-fluid">
                 <a href="<?= Yii::$app->urlManager->createUrl(['site/dashboard','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/analytic.png') ?></i>
                                        <div>Dashboard</div>

                                </a>
                              <a href="<?= Yii::$app->urlManager->createUrl(['/application/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/jobcardassign.png') ?></i>
                                        <div>Application</div>

                                </a>
                                <a href="<?= Yii::$app->urlManager->createUrl(['/allocation/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                          <i><?php echo Html::img('@web/image/Logbook.png') ?></i>
                                        <div>Allocation</div>

                                </a>
                          <a href="<?= Yii::$app->urlManager->createUrl(['/disbursement/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/transaction12.png') ?></i>
                                        <div>Disbursement</div>

                                </a>
             </div>
                
                               <a href="<?= Yii::$app->urlManager->createUrl(['/repayment/default','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/transaction.png') ?></i>
                                        <div>Repayment</div>

                                </a>
                               <a href="<?= Yii::$app->urlManager->createUrl(['site/lookup','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/Set3.png') ?></i>
                                        <div>Look Up</div>

                                </a>
                              <a href="<?= Yii::$app->urlManager->createUrl(['site/index','id'=>1])?>" class="btn btn-app" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/Report.png') ?></i>
                                        <div>Reports</div>

                                </a>
                      
                              </div>
                             </div>
                   
                </div>     

backend/views/site/indexb.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
//$this->title = 'ASSETS  MANAGEMENT SYSTEM';
//$this->title = 'About';
//$this->params['breadcrumbs'][] = $this->title;
?>
<style>
.icon-btn {
    height: 70px;
    width: 50px;
    margin: 10px 0px 10px 0px;
    border: 1px solid #ddd;
    padding: 16px 0px 0px 0px;
    background-color: #fafafa !important;
    background-image: none !important;
    filter: none !important;
    -webkit-box-shadow: none !important;
    -moz-box-shadow: none !important;
    box-shadow: none !important;
    display: block !important;
    color: #646464 !important;
    text-shadow: none !important;
    text-align: center;
    cursor: pointer;
    position: relative;
    -webkit-transition: all 0.3s ease !important;
    -moz-transition: all 0.3s ease !important;
    -ms-transition: all 0.3s ease !important;
    -o-transition: all 0.3s ease !important;
    transition: all 0.3s ease !important;
}

</style>
 <div class="box box-info">
            <div class="box-header with-border">
               <h3 class="box-title">Home Page</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
             <div class="row-fluid">
                 <a href="<?= Yii::$app->urlManager->createUrl(['site/index','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/analytic.png') ?></i>
                                        <div>Dashboard</div>

                                </a>
                            
                                <a href="<?= Yii::$app->urlManager->createUrl(['memberinfo/viewb','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/pastor.png') ?></i>
                                        <div>My Profile</div>

                                </a>
                             </div>
                        <div class="row-fluid">
                                 <a href="<?= Yii::$app->urlManager->createUrl(['group/indexb','id'=>1])?>" class="icon-btn span2" style="min-height:180px">
                                        <i><?php echo Html::img('@web/image/group12.png') ?></i>
                                        <div>Group</div>

                                </a>
                              </div>
                             </div>
                   
                </div>     

backend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>